export type RegionCode = string;
export type CountryCode = string;

export interface Country {
  code: CountryCode;
  name: string;
  region: RegionCode; // Used for fallback calculation
}

export const REGIONS = [
  { code: 'EU', name: 'Union Européenne' },
  { code: 'ROW', name: 'Reste du Monde' },
];

export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afghanistan', region: 'ROW' },
  { code: 'ZA', name: 'Afrique du Sud', region: 'ROW' },
  { code: 'AL', name: 'Albanie', region: 'ROW' },
  { code: 'DZ', name: 'Algérie', region: 'ROW' },
  { code: 'DE', name: 'Allemagne', region: 'EU' },
  { code: 'AD', name: 'Andorre', region: 'ROW' },
  { code: 'AO', name: 'Angola', region: 'ROW' },
  { code: 'AI', name: 'Anguilla', region: 'ROW' },
  { code: 'AQ', name: 'Antarctique', region: 'ROW' },
  { code: 'AG', name: 'Antigua-et-Barbuda', region: 'ROW' },
  { code: 'SA', name: 'Arabie saoudite', region: 'ROW' },
  { code: 'AR', name: 'Argentine', region: 'ROW' },
  { code: 'AM', name: 'Arménie', region: 'ROW' },
  { code: 'AW', name: 'Aruba', region: 'ROW' },
  { code: 'AU', name: 'Australie', region: 'ROW' },
  { code: 'AT', name: 'Autriche', region: 'EU' },
  { code: 'AZ', name: 'Azerbaïdjan', region: 'ROW' },
  { code: 'BS', name: 'Bahamas', region: 'ROW' },
  { code: 'BH', name: 'Bahreïn', region: 'ROW' },
  { code: 'BD', name: 'Bangladesh', region: 'ROW' },
  { code: 'BB', name: 'Barbade', region: 'ROW' },
  { code: 'BE', name: 'Belgique', region: 'EU' },
  { code: 'BZ', name: 'Belize', region: 'ROW' },
  { code: 'BM', name: 'Bermudes', region: 'ROW' },
  { code: 'BT', name: 'Bhoutan', region: 'ROW' },
  { code: 'BY', name: 'Biélorussie', region: 'ROW' },
  { code: 'BO', name: 'Bolivie', region: 'ROW' },
  { code: 'BA', name: 'Bosnie-Herzégovine', region: 'ROW' },
  { code: 'BW', name: 'Botswana', region: 'ROW' },
  { code: 'BN', name: 'Brunéi Darussalam', region: 'ROW' },
  { code: 'BR', name: 'Brésil', region: 'ROW' },
  { code: 'BG', name: 'Bulgarie', region: 'EU' },
  { code: 'BF', name: 'Burkina Faso', region: 'ROW' },
  { code: 'BI', name: 'Burundi', region: 'ROW' },
  { code: 'BJ', name: 'Bénin', region: 'ROW' },
  { code: 'KH', name: 'Cambodge', region: 'ROW' },
  { code: 'CM', name: 'Cameroun', region: 'ROW' },
  { code: 'CA', name: 'Canada', region: 'ROW' },
  { code: 'CV', name: 'Cap-Vert', region: 'ROW' },
  { code: 'CL', name: 'Chili', region: 'ROW' },
  { code: 'CN', name: 'Chine', region: 'ROW' },
  { code: 'CY', name: 'Chypre', region: 'EU' },
  { code: 'CO', name: 'Colombie', region: 'ROW' },
  { code: 'KM', name: 'Comores', region: 'ROW' },
  { code: 'CG', name: 'Congo-Brazzaville', region: 'ROW' },
  { code: 'CD', name: 'Congo-Kinshasa', region: 'ROW' },
  { code: 'KP', name: 'Corée du Nord', region: 'ROW' },
  { code: 'KR', name: 'Corée du Sud', region: 'ROW' },
  { code: 'CR', name: 'Costa Rica', region: 'ROW' },
  { code: 'HR', name: 'Croatie', region: 'EU' },
  { code: 'CU', name: 'Cuba', region: 'ROW' },
  { code: 'CW', name: 'Curaçao', region: 'ROW' },
  { code: 'CI', name: 'Côte d’Ivoire', region: 'ROW' },
  { code: 'DK', name: 'Danemark', region: 'EU' },
  { code: 'DJ', name: 'Djibouti', region: 'ROW' },
  { code: 'DM', name: 'Dominique', region: 'ROW' },
  { code: 'ES', name: 'Espagne', region: 'EU' },
  { code: 'EE', name: 'Estonie', region: 'EU' },
  { code: 'SZ', name: 'Eswatini', region: 'ROW' },
  { code: 'FJ', name: 'Fidji', region: 'ROW' },
  { code: 'FI', name: 'Finlande', region: 'EU' },
  { code: 'FR', name: 'France', region: 'EU' },
  { code: 'GA', name: 'Gabon', region: 'ROW' },
  { code: 'GM', name: 'Gambie', region: 'ROW' },
  { code: 'GH', name: 'Ghana', region: 'ROW' },
  { code: 'GI', name: 'Gibraltar', region: 'ROW' },
  { code: 'GD', name: 'Grenade', region: 'ROW' },
  { code: 'GL', name: 'Groenland', region: 'ROW' },
  { code: 'GR', name: 'Grèce', region: 'EU' },
  { code: 'GP', name: 'Guadeloupe', region: 'ROW' },
  { code: 'GU', name: 'Guam', region: 'ROW' },
  { code: 'GT', name: 'Guatemala', region: 'ROW' },
  { code: 'GG', name: 'Guernesey', region: 'ROW' },
  { code: 'GN', name: 'Guinée', region: 'ROW' },
  { code: 'GQ', name: 'Guinée équatoriale', region: 'ROW' },
  { code: 'GW', name: 'Guinée-Bissau', region: 'ROW' },
  { code: 'GY', name: 'Guyana', region: 'ROW' },
  { code: 'GF', name: 'Guyane française', region: 'ROW' },
  { code: 'GE', name: 'Géorgie', region: 'ROW' },
  { code: 'GS', name: 'Géorgie du Sud et îles Sandwich du Sud', region: 'ROW' },
  { code: 'HT', name: 'Haïti', region: 'ROW' },
  { code: 'HN', name: 'Honduras', region: 'ROW' },
  { code: 'HU', name: 'Hongrie', region: 'EU' },
  { code: 'IN', name: 'Inde', region: 'ROW' },
  { code: 'ID', name: 'Indonésie', region: 'ROW' },
  { code: 'IQ', name: 'Irak', region: 'ROW' },
  { code: 'IR', name: 'Iran', region: 'ROW' },
  { code: 'IE', name: 'Irlande', region: 'EU' },
  { code: 'IS', name: 'Islande', region: 'ROW' },
  { code: 'IL', name: 'Israël', region: 'ROW' },
  { code: 'IT', name: 'Italie', region: 'EU' },
  { code: 'JM', name: 'Jamaïque', region: 'ROW' },
  { code: 'JP', name: 'Japon', region: 'ROW' },
  { code: 'JE', name: 'Jersey', region: 'ROW' },
  { code: 'JO', name: 'Jordanie', region: 'ROW' },
  { code: 'KZ', name: 'Kazakhstan', region: 'ROW' },
  { code: 'KE', name: 'Kenya', region: 'ROW' },
  { code: 'KG', name: 'Kirghizistan', region: 'ROW' },
  { code: 'KI', name: 'Kiribati', region: 'ROW' },
  { code: 'KW', name: 'Koweït', region: 'ROW' },
  { code: 'RE', name: 'La Réunion', region: 'ROW' },
  { code: 'LA', name: 'Laos', region: 'ROW' },
  { code: 'LS', name: 'Lesotho', region: 'ROW' },
  { code: 'LV', name: 'Lettonie', region: 'EU' },
  { code: 'LB', name: 'Liban', region: 'ROW' },
  { code: 'LY', name: 'Libye', region: 'ROW' },
  { code: 'LR', name: 'Libéria', region: 'ROW' },
  { code: 'LI', name: 'Liechtenstein', region: 'ROW' },
  { code: 'LT', name: 'Lituanie', region: 'EU' },
  { code: 'LU', name: 'Luxembourg', region: 'EU' },
  { code: 'MK', name: 'Macédoine du Nord', region: 'ROW' },
  { code: 'MG', name: 'Madagascar', region: 'ROW' },
  { code: 'MY', name: 'Malaisie', region: 'ROW' },
  { code: 'MW', name: 'Malawi', region: 'ROW' },
  { code: 'MV', name: 'Maldives', region: 'ROW' },
  { code: 'ML', name: 'Mali', region: 'ROW' },
  { code: 'MT', name: 'Malte', region: 'EU' },
  { code: 'MA', name: 'Maroc', region: 'ROW' },
  { code: 'MQ', name: 'Martinique', region: 'ROW' },
  { code: 'MU', name: 'Maurice', region: 'ROW' },
  { code: 'MR', name: 'Mauritanie', region: 'ROW' },
  { code: 'YT', name: 'Mayotte', region: 'ROW' },
  { code: 'MX', name: 'Mexique', region: 'ROW' },
  { code: 'MD', name: 'Moldavie', region: 'ROW' },
  { code: 'MC', name: 'Monaco', region: 'ROW' },
  { code: 'MN', name: 'Mongolie', region: 'ROW' },
  { code: 'MS', name: 'Montserrat', region: 'ROW' },
  { code: 'ME', name: 'Monténégro', region: 'ROW' },
  { code: 'MZ', name: 'Mozambique', region: 'ROW' },
  { code: 'MM', name: 'Myanmar (Birmanie)', region: 'ROW' },
  { code: 'NA', name: 'Namibie', region: 'ROW' },
  { code: 'NR', name: 'Nauru', region: 'ROW' },
  { code: 'NI', name: 'Nicaragua', region: 'ROW' },
  { code: 'NE', name: 'Niger', region: 'ROW' },
  { code: 'NG', name: 'Nigéria', region: 'ROW' },
  { code: 'NU', name: 'Niue', region: 'ROW' },
  { code: 'NO', name: 'Norvège', region: 'ROW' },
  { code: 'NC', name: 'Nouvelle-Calédonie', region: 'ROW' },
  { code: 'NZ', name: 'Nouvelle-Zélande', region: 'ROW' },
  { code: 'NP', name: 'Népal', region: 'ROW' },
  { code: 'OM', name: 'Oman', region: 'ROW' },
  { code: 'UG', name: 'Ouganda', region: 'ROW' },
  { code: 'UZ', name: 'Ouzbékistan', region: 'ROW' },
  { code: 'PK', name: 'Pakistan', region: 'ROW' },
  { code: 'PW', name: 'Palaos', region: 'ROW' },
  { code: 'PA', name: 'Panama', region: 'ROW' },
  { code: 'PG', name: 'Papouasie-Nouvelle-Guinée', region: 'ROW' },
  { code: 'PY', name: 'Paraguay', region: 'ROW' },
  { code: 'NL', name: 'Pays-Bas', region: 'EU' },
  { code: 'BQ', name: 'Pays-Bas caribéens', region: 'ROW' },
  { code: 'PH', name: 'Philippines', region: 'ROW' },
  { code: 'PL', name: 'Pologne', region: 'EU' },
  { code: 'PF', name: 'Polynésie française', region: 'ROW' },
  { code: 'PR', name: 'Porto Rico', region: 'ROW' },
  { code: 'PT', name: 'Portugal', region: 'EU' },
  { code: 'PE', name: 'Pérou', region: 'ROW' },
  { code: 'QA', name: 'Qatar', region: 'ROW' },
  { code: 'HK', name: 'R.A.S. chinoise de Hong Kong', region: 'ROW' },
  { code: 'MO', name: 'R.A.S. chinoise de Macao', region: 'ROW' },
  { code: 'RO', name: 'Roumanie', region: 'EU' },
  { code: 'GB', name: 'Royaume-Uni', region: 'ROW' },
  { code: 'RU', name: 'Russie', region: 'ROW' },
  { code: 'RW', name: 'Rwanda', region: 'ROW' },
  { code: 'CF', name: 'République centrafricaine', region: 'ROW' },
  { code: 'DO', name: 'République dominicaine', region: 'ROW' },
  { code: 'EH', name: 'Sahara occidental', region: 'ROW' },
  { code: 'BL', name: 'Saint-Barthélemy', region: 'ROW' },
  { code: 'KN', name: 'Saint-Christophe-et-Niévès', region: 'ROW' },
  { code: 'SM', name: 'Saint-Marin', region: 'ROW' },
  { code: 'MF', name: 'Saint-Martin', region: 'ROW' },
  { code: 'SX', name: 'Saint-Martin (partie néerlandaise)', region: 'ROW' },
  { code: 'PM', name: 'Saint-Pierre-et-Miquelon', region: 'ROW' },
  { code: 'VC', name: 'Saint-Vincent-et-les-Grenadines', region: 'ROW' },
  { code: 'SH', name: 'Sainte-Hélène', region: 'ROW' },
  { code: 'LC', name: 'Sainte-Lucie', region: 'ROW' },
  { code: 'SV', name: 'Salvador', region: 'ROW' },
  { code: 'WS', name: 'Samoa', region: 'ROW' },
  { code: 'AS', name: 'Samoa américaines', region: 'ROW' },
  { code: 'ST', name: 'Sao Tomé-et-Principe', region: 'ROW' },
  { code: 'RS', name: 'Serbie', region: 'ROW' },
  { code: 'SC', name: 'Seychelles', region: 'ROW' },
  { code: 'SL', name: 'Sierra Leone', region: 'ROW' },
  { code: 'SG', name: 'Singapour', region: 'ROW' },
  { code: 'SK', name: 'Slovaquie', region: 'EU' },
  { code: 'SI', name: 'Slovénie', region: 'EU' },
  { code: 'SO', name: 'Somalie', region: 'ROW' },
  { code: 'SD', name: 'Soudan', region: 'ROW' },
  { code: 'SS', name: 'Soudan du Sud', region: 'ROW' },
  { code: 'LK', name: 'Sri Lanka', region: 'ROW' },
  { code: 'CH', name: 'Suisse', region: 'ROW' },
  { code: 'SR', name: 'Suriname', region: 'ROW' },
  { code: 'SE', name: 'Suède', region: 'EU' },
  { code: 'SJ', name: 'Svalbard et Jan Mayen', region: 'ROW' },
  { code: 'SY', name: 'Syrie', region: 'ROW' },
  { code: 'SN', name: 'Sénégal', region: 'ROW' },
  { code: 'TJ', name: 'Tadjikistan', region: 'ROW' },
  { code: 'TZ', name: 'Tanzanie', region: 'ROW' },
  { code: 'TW', name: 'Taïwan', region: 'ROW' },
  { code: 'TD', name: 'Tchad', region: 'ROW' },
  { code: 'CZ', name: 'Tchéquie', region: 'EU' },
  { code: 'TF', name: 'Terres australes françaises', region: 'ROW' },
  { code: 'IO', name: 'Territoire britannique de l’océan Indien', region: 'ROW' },
  { code: 'PS', name: 'Territoires palestiniens', region: 'ROW' },
  { code: 'TH', name: 'Thaïlande', region: 'ROW' },
  { code: 'TL', name: 'Timor oriental', region: 'ROW' },
  { code: 'TG', name: 'Togo', region: 'ROW' },
  { code: 'TK', name: 'Tokelau', region: 'ROW' },
  { code: 'TO', name: 'Tonga', region: 'ROW' },
  { code: 'TT', name: 'Trinité-et-Tobago', region: 'ROW' },
  { code: 'TN', name: 'Tunisie', region: 'ROW' },
  { code: 'TM', name: 'Turkménistan', region: 'ROW' },
  { code: 'TR', name: 'Turquie', region: 'ROW' },
  { code: 'TV', name: 'Tuvalu', region: 'ROW' },
  { code: 'UA', name: 'Ukraine', region: 'ROW' },
  { code: 'UY', name: 'Uruguay', region: 'ROW' },
  { code: 'VU', name: 'Vanuatu', region: 'ROW' },
  { code: 'VE', name: 'Venezuela', region: 'ROW' },
  { code: 'VN', name: 'Vietnam', region: 'ROW' },
  { code: 'WF', name: 'Wallis-et-Futuna', region: 'ROW' },
  { code: 'YE', name: 'Yémen', region: 'ROW' },
  { code: 'ZM', name: 'Zambie', region: 'ROW' },
  { code: 'ZW', name: 'Zimbabwe', region: 'ROW' },
  { code: 'EG', name: 'Égypte', region: 'ROW' },
  { code: 'AE', name: 'Émirats arabes unis', region: 'ROW' },
  { code: 'EC', name: 'Équateur', region: 'ROW' },
  { code: 'ER', name: 'Érythrée', region: 'ROW' },
  { code: 'VA', name: 'État de la Cité du Vatican', region: 'ROW' },
  { code: 'FM', name: 'États fédérés de Micronésie', region: 'ROW' },
  { code: 'US', name: 'États-Unis', region: 'ROW' },
  { code: 'ET', name: 'Éthiopie', region: 'ROW' },
  { code: 'BV', name: 'Île Bouvet', region: 'ROW' },
  { code: 'CX', name: 'Île Christmas', region: 'ROW' },
  { code: 'NF', name: 'Île Norfolk', region: 'ROW' },
  { code: 'IM', name: 'Île de Man', region: 'ROW' },
  { code: 'KY', name: 'Îles Caïmans', region: 'ROW' },
  { code: 'CC', name: 'Îles Cocos', region: 'ROW' },
  { code: 'CK', name: 'Îles Cook', region: 'ROW' },
  { code: 'FO', name: 'Îles Féroé', region: 'ROW' },
  { code: 'HM', name: 'Îles Heard et McDonald', region: 'ROW' },
  { code: 'FK', name: 'Îles Malouines', region: 'ROW' },
  { code: 'MP', name: 'Îles Mariannes du Nord', region: 'ROW' },
  { code: 'MH', name: 'Îles Marshall', region: 'ROW' },
  { code: 'PN', name: 'Îles Pitcairn', region: 'ROW' },
  { code: 'SB', name: 'Îles Salomon', region: 'ROW' },
  { code: 'TC', name: 'Îles Turques-et-Caïques', region: 'ROW' },
  { code: 'VG', name: 'Îles Vierges britanniques', region: 'ROW' },
  { code: 'VI', name: 'Îles Vierges des États-Unis', region: 'ROW' },
  { code: 'UM', name: 'Îles mineures éloignées des États-Unis', region: 'ROW' },
  { code: 'AX', name: 'Îles Åland', region: 'ROW' },
];

export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find(c => c.code === code);
}
